name: Clang Format Check

on:
  pull_request:
    paths:
      - '**/*.cpp'
      - '**/*.h'
  push:
    paths:
      - '**/*.cpp'
      - '**/*.h'

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Check formatting
        run: |
          find . -name "*.cpp" -o -name "*.h" | xargs clang-format -style=file -output-replacements-xml | grep "<replacement " && exit 1 || exit 0
