name: Clang-Tidy Check

on:
  push:
    paths:
      - '**/*.cpp'
      - '**/*.h'
  pull_request:
    paths:
      - '**/*.cpp'
      - '**/*.h'

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy qtbase5-dev qtbase5-dev-tools qtdeclarative5-dev qt5-qmake

      - name: Debug QtCore headers
        run: ls -l /usr/include/qt5/QtCore
        
      - name: Run clang-tidy
        run: |
          PROJECT_ROOT=$(pwd)
          for file in $(find . -path ./build -prune -o -name "*.cpp" -print); do
            echo "Checking $file"
            clang-tidy "$file" --header-filter="^$PROJECT_ROOT/" -- \
              -I . \
              -isystem /usr/include/qt5 \
              -isystem /usr/include/x86_64-linux-gnu/qt5 \
              -isystem /usr/include/qt5/QtCore \
              -isystem /usr/include/qt5/QtGui \
              -isystem /usr/include/qt5/QtWidgets \
              -isystem /usr/include/qt5/QtNetwork \
              -isystem /usr/include/qt5/QtQml \
              -std=c++17
          done

